# Generated by Django 5.2 on 2025-05-10 20:48

import TechShopApp.models
import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام رنگ')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#008000', 'green'), ('#0000FF', 'blue')], verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'رنگ پایه',
                'verbose_name_plural': 'رنگ های پایه',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام ---فارسی')),
                ('en_name', models.CharField(max_length=50, unique=True, verbose_name='نام ---انگلیسی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=TechShopApp.models.upload_brand_image_path, verbose_name='لوگو برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('4XL', '4XL')], max_length=10, null=True, verbose_name='سایز')),
                ('number_size', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سایز عددی (برای مواردی مثل کفش)')),
                ('size_numrical', models.CharField(blank=True, max_length=10, null=True, verbose_name='سایز عددی نوشتاری')),
                ('category', models.CharField(blank=True, choices=[('clothing', 'لباس'), ('shoes', 'کفش'), ('accessories', 'اکسسوری')], max_length=20, null=True, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایزها',
                'ordering': ['number_size'],
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BaseCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم  --  فارسی --  دسته بندی اصلی')),
                ('en_name', models.CharField(max_length=50, unique=True, verbose_name='اسم- --انگلیسی-- دسته بندی اصلی')),
                ('description', models.TextField(verbose_name='توضیحات دسته بندی اصلی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=TechShopApp.models.upload_BaseCategory_image_path, verbose_name='عکس دسته بندی اصلی')),
                ('brands', models.ManyToManyField(blank=True, related_name='base_categories', to='TechShopApp.brand', verbose_name='برند های دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی  اصلی ',
                'verbose_name_plural': 'دسته بندی های اصلی',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='نام دسته بندی ---فارسی')),
                ('en_name', models.CharField(max_length=20, unique=True, verbose_name='نام دسته بندی ---انگلیسی')),
                ('description', models.TextField(verbose_name='توضیحات دسته بندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=TechShopApp.models.upload_cat_image_path, verbose_name='عکس دسته بندی')),
                ('base_catgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='TechShopApp.basecategorys', verbose_name='دسته بندی اصلی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='TechShopApp.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, to='TechShopApp.category', verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام ویژگی')),
                ('title', models.CharField(default='ویژگی تعریف نشده', max_length=50, verbose_name='عنوان ویژگی')),
                ('value', models.TextField(verbose_name='توضیحات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'ویژگی دسته بندی',
                'verbose_name_plural': 'ویژگی های دسته بندی',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='categories', to='TechShopApp.categoryattribute', verbose_name='ویژگی ها'),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام رنگ')),
                ('hex_code', models.CharField(help_text=' مثال: #FFFFFF', max_length=7, verbose_name='کد هگز رنگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=TechShopApp.models.upload_color_image_path, verbose_name='تصویر رنگ')),
                ('base_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='TechShopApp.basecolor', verbose_name='رنگ پایه')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='موجود')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان اضافه شدن')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='عکس')),
                ('categories', models.ManyToManyField(to='TechShopApp.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=TechShopApp.models.upload_image_path, verbose_name='عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'گالری',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='TechShopApp.comment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='مقدار ویژگی')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.categoryattribute', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی های محصول',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='TechShopApp.productattribute', verbose_name='ویژگی ها'),
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(blank=True, choices=[('4T', '4 ترابایت'), ('2T', '2 ترابایت'), ('1T', '1 ترابایت'), ('512', '512 گیگابایت'), ('256', '256 گیگابایت'), ('128', '128 گیگابایت'), ('64', '64 گیگابایت'), ('32', '32 گیگابایت'), ('16', '16 گیگابایت'), ('8', '8 گیگابایت'), ('4', '4 گیگابایت'), ('2', '2 گیگابایت'), ('1', '1 گیگابایت')], max_length=10, null=True, verbose_name='سایز حافظه')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('weight', models.PositiveIntegerField(blank=True, default=0, verbose_name='وزن به گرم')),
                ('is_active_package', models.BooleanField(default=False, verbose_name=' موجود ؟')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.BigIntegerField(verbose_name='قیمت برای این ویژگی ها')),
                ('final_price', models.BigIntegerField(default=0, editable=False, verbose_name='  قیمت نهایی با این ویژگی ها ')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='درصد تخفیف')),
                ('is_active_discount', models.BooleanField(default=False, verbose_name='اعمال تخفیف')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packages', to='TechShopApp.product')),
                ('size', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.size')),
            ],
            options={
                'verbose_name': ' ویژگی های محصول',
                'verbose_name_plural': ' ویژگی های محصولات',
            },
        ),
    ]
