# Generated by Django 5.2 on 2025-05-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechShopApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
