# Generated by Django 5.2 on 2025-05-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpackage',
            name='brand',
        ),
        migrations.AlterField(
            model_name='size',
            name='size_numrical',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='سایز عددی نوشتاری'),
        ),
    ]
