# Generated by Django 5.2 on 2025-05-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechShopApp', '0002_remove_productpackage_brand_alter_size_size_numrical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackage',
            name='size',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.size'),
        ),
    ]
