# Generated by Django 5.2 on 2025-05-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechShopApp', '0002_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryattribute',
            name='name',
        ),
    ]
