# Generated by Django 5.2 on 2025-05-05 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechShopApp', '0003_alter_productpackage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.color', verbose_name='رنگ'),
        ),
    ]
