# Generated by Django 5.2 on 2025-05-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechShopApp', '0003_remove_categoryattribute_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryattribute',
            old_name='value',
            new_name='description',
        ),
    ]
