# Generated by Django 5.2 on 2025-05-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechShopApp', '0004_alter_productpackage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackage',
            name='storage',
            field=models.CharField(blank=True, choices=[('2T', '2 ترابایت'), ('1T', '1 ترابایت'), ('512', '512 گیگابایت'), ('256', '256 گیگابایت'), ('128', '128 گیگابایت'), ('64', '64 گیگابایت'), ('32', '32 گیگابایت'), ('16', '16 گیگابایت'), ('8', '8 گیگابایت'), ('4', '4 گیگابایت'), ('2', '2 گیگابایت'), ('1', '1 گیگابایت')], max_length=10, null=True, verbose_name='سایز حافظه'),
        ),
    ]
