# Generated by Django 5.2 on 2025-05-10 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechShopApp', '0006_alter_productpackage_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(default='ویژگی تعریف نشده ', max_length=50)),
                ('value', models.TextField(verbose_name='توضیحات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.category', verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='product_attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.category_attributes', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.product', verbose_name='محصول')),
            ],
        ),
    ]
