# Generated by Django 5.2 on 2025-05-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechShopApp', '0007_category_attributes_product_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_attributes',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.category_attributes', verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='product_attributes',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TechShopApp.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='product_attributes',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
