# Generated by Django 5.2 on 2025-05-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechShopApp', '0008_alter_product_attributes_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_attributes',
            name='name',
        ),
    ]
